Listing '.'...
Listing './bin'...
Listing './include'...
Listing './lib'...
Listing './lib/python3.5'...
Listing './lib/python3.5/site-packages'...
Listing './lib/python3.5/site-packages/astroid'...
Listing './lib/python3.5/site-packages/astroid/brain'...
Listing './lib/python3.5/site-packages/astroid/interpreter'...
Listing './lib/python3.5/site-packages/astroid/interpreter/_import'...
Listing './lib/python3.5/site-packages/astroid/tests'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/SSL1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/absimp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/absimp/sidepackage'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/all.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/all.py", line 7
    def func(): print 'yo'
                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/appl'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/contribute_to_namespace'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/contribute_to_namespace/namespace_pep_420'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/find_test'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/foogle'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/foogle/fax'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/invalid_encoding.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/invalid_encoding.py", line 0
SyntaxError: unknown encoding: lala

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/lmfp'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module.py", line 32
    except ValueError, ex:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module1abs'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module2.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module2.py", line 78
    exec 'c = 3'
               ^
SyntaxError: Missing parentheses in call to 'exec'

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/namespace_pep_420'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/noendingnewline.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/noendingnewline.py", line 21
    print 'a'
            ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/notamodule'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/package/subpackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/unicode_package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/unicode_package/core'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/SSL1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/absimp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/absimp/sidepackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/appl'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/contribute_to_namespace'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/contribute_to_namespace/namespace_pep_420'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/find_test'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/foogle'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/foogle/fax'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/invalid_encoding.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python3/data/invalid_encoding.py", line 0
SyntaxError: unknown encoding: lala

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/lmfp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/module1abs'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/namespace_pep_420'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/notamodule'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/package/subpackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/unicode_package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/unicode_package/core'...
Listing './lib/python3.5/site-packages/astroid-1.6.0.dist-info'...
Listing './lib/python3.5/site-packages/flake8'...
Listing './lib/python3.5/site-packages/flake8/tests'...
Listing './lib/python3.5/site-packages/flake8-2.4.1.dist-info'...
Listing './lib/python3.5/site-packages/flake8_quotes'...
Listing './lib/python3.5/site-packages/flake8_quotes-0.0.1.egg-info'...
Listing './lib/python3.5/site-packages/frozendict'...
Listing './lib/python3.5/site-packages/frozendict-0.4.egg-info'...
Listing './lib/python3.5/site-packages/frozenordereddict'...
Listing './lib/python3.5/site-packages/frozenordereddict-1.2.0.egg-info'...
Listing './lib/python3.5/site-packages/invoke'...
Listing './lib/python3.5/site-packages/invoke/parser'...
Listing './lib/python3.5/site-packages/invoke/vendor'...
Listing './lib/python3.5/site-packages/invoke/vendor/fluidity'...
Listing './lib/python3.5/site-packages/invoke/vendor/lexicon'...
Listing './lib/python3.5/site-packages/invoke/vendor/yaml2'...
Compiling './lib/python3.5/site-packages/invoke/vendor/yaml2/constructor.py'...
***   File "./lib/python3.5/site-packages/invoke/vendor/yaml2/constructor.py", line 130
    except TypeError, exc:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/invoke/vendor/yaml2/reader.py'...
***   File "./lib/python3.5/site-packages/invoke/vendor/yaml2/reader.py", line 158
    except UnicodeDecodeError, exc:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/invoke/vendor/yaml2/resolver.py'...
***   File "./lib/python3.5/site-packages/invoke/vendor/yaml2/resolver.py", line 171
    re.compile(ur'''^(?:yes|Yes|YES|no|No|NO
                    |true|True|TRUE|false|False|FALSE
                    |on|On|ON|off|Off|OFF)$''', re.X),
                                            
                                                     
                                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/invoke/vendor/yaml2/scanner.py'...
***   File "./lib/python3.5/site-packages/invoke/vendor/yaml2/scanner.py", line 1427
    except UnicodeDecodeError, exc:
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/invoke/vendor/yaml3'...
Listing './lib/python3.5/site-packages/invoke-0.10.1.dist-info'...
Listing './lib/python3.5/site-packages/lazy_object_proxy'...
Listing './lib/python3.5/site-packages/lazy_object_proxy-1.3.1.dist-info'...
Listing './lib/python3.5/site-packages/liquidnitrogen'...
Listing './lib/python3.5/site-packages/liquidnitrogen-0.0.0.egg-info'...
Listing './lib/python3.5/site-packages/logilab'...
Listing './lib/python3.5/site-packages/logilab/common'...
Listing './lib/python3.5/site-packages/logilab/common/ureports'...
Listing './lib/python3.5/site-packages/logilab_common-1.4.1.egg-info'...
Listing './lib/python3.5/site-packages/mccabe-0.3.1.dist-info'...
Listing './lib/python3.5/site-packages/nose'...
Listing './lib/python3.5/site-packages/nose/ext'...
Listing './lib/python3.5/site-packages/nose/plugins'...
Listing './lib/python3.5/site-packages/nose/sphinx'...
Listing './lib/python3.5/site-packages/nose/tools'...
Listing './lib/python3.5/site-packages/nose-1.3.7.dist-info'...
Listing './lib/python3.5/site-packages/pep8-1.6.2.dist-info'...
Listing './lib/python3.5/site-packages/pip'...
Listing './lib/python3.5/site-packages/pip/_vendor'...
Listing './lib/python3.5/site-packages/pip/commands'...
Listing './lib/python3.5/site-packages/pip/compat'...
Listing './lib/python3.5/site-packages/pip/models'...
Listing './lib/python3.5/site-packages/pip/operations'...
Listing './lib/python3.5/site-packages/pip/req'...
Listing './lib/python3.5/site-packages/pip/utils'...
Listing './lib/python3.5/site-packages/pip/vcs'...
Listing './lib/python3.5/site-packages/pip-9.0.1.dist-info'...
Listing './lib/python3.5/site-packages/pkg_resources'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor/packaging'...
Listing './lib/python3.5/site-packages/pkg_resources/extern'...
Listing './lib/python3.5/site-packages/pkg_resources-0.0.0.dist-info'...
Listing './lib/python3.5/site-packages/pyflakes'...
Listing './lib/python3.5/site-packages/pyflakes/scripts'...
Listing './lib/python3.5/site-packages/pyflakes/test'...
Listing './lib/python3.5/site-packages/pyflakes-0.8.1.dist-info'...
Listing './lib/python3.5/site-packages/pylint'...
Listing './lib/python3.5/site-packages/pylint/checkers'...
Listing './lib/python3.5/site-packages/pylint/pyreverse'...
Listing './lib/python3.5/site-packages/pylint/reporters'...
Listing './lib/python3.5/site-packages/pylint/test'...
Listing './lib/python3.5/site-packages/pylint/test/data'...
Listing './lib/python3.5/site-packages/pylint/test/functional'...
Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_outside_func.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_outside_func.py", line 2
    yield 1  # [yield-outside-function]
                                      ^
SyntaxError: 'yield' outside function

Listing './lib/python3.5/site-packages/pylint/test/input'...
Compiling './lib/python3.5/site-packages/pylint/test/input/func_continue_not_in_loop.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_continue_not_in_loop.py", line 8
    continue
    ^
SyntaxError: 'continue' not properly in loop

Compiling './lib/python3.5/site-packages/pylint/test/input/func_e0001_py30.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_e0001_py30.py", line 12
    raise 'exception', 'message'
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/input/func_e0108.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_e0108.py", line 4
    def foo1(_, _):
                  ^
SyntaxError: duplicate argument '_' in function definition

Compiling './lib/python3.5/site-packages/pylint/test/input/func_keyword_repeat.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_keyword_repeat.py", line 8
    function_default_arg(two=5, two=7)
                               ^
SyntaxError: keyword argument repeated

Compiling './lib/python3.5/site-packages/pylint/test/input/func_return_outside_func.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_return_outside_func.py", line 3
    return
         ^
SyntaxError: 'return' outside function

Compiling './lib/python3.5/site-packages/pylint/test/input/func_syntax_error.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_syntax_error.py", line 1
    def toto
           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint/test/input/func_w0401_package'...
Compiling './lib/python3.5/site-packages/pylint/test/input/func_w0705.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_w0705.py", line 28
    __revision__ += 1
                   ^
SyntaxError: default 'except:' must be last

Compiling './lib/python3.5/site-packages/pylint/test/input/syntax_error.py'...
*** Sorry: IndentationError: expected an indented block (syntax_error.py, line 2)
Listing './lib/python3.5/site-packages/pylint/test/messages'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/absimp'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package/subpackage'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package_all'...
Listing './lib/python3.5/site-packages/pylint-1.4.4.dist-info'...
Listing './lib/python3.5/site-packages/setuptools'...
Listing './lib/python3.5/site-packages/setuptools/command'...
Listing './lib/python3.5/site-packages/setuptools/extern'...
Listing './lib/python3.5/site-packages/setuptools-32.3.1.dist-info'...
Listing './lib/python3.5/site-packages/six-1.11.0.dist-info'...
Listing './lib/python3.5/site-packages/tests'...
Listing './lib/python3.5/site-packages/wrapt'...
Listing './lib/python3.5/site-packages/wrapt-1.10.11.egg-info'...
Listing './man'...
Listing './man/man1'...
Listing './share'...
Listing './share/python-wheels'...
