Listing '.'...
Listing './bin'...
Listing './include'...
Listing './lib'...
Listing './lib/python3.5'...
Listing './lib/python3.5/site-packages'...
Listing './lib/python3.5/site-packages/google'...
Listing './lib/python3.5/site-packages/google/appengine'...
Listing './lib/python3.5/site-packages/google/appengine/_internal'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/antlr3'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/antlr3/extras.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/antlr3/extras.py", line 45
    except ImportError, exc:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/antlr3/recognizers.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/antlr3/recognizers.py", line 1130
    except NoViableAltException, re:
                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/conf'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/conf/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/conf/__init__.py", line 58
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/conf/app_template'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/conf/locale'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/conf/locale/en'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/conf/project_template'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/conf/urls'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/cache'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/cache/backends'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/files'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/files/move.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/files/move.py", line 82
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/files/storage.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/files/storage.py", line 173
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/files/uploadedfile.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/files/uploadedfile.py", line 78
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/files/uploadhandler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/files/uploadhandler.py", line 207
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/handlers'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/handlers/base.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/handlers/base.py", line 41
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/mail'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/mail/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/mail/__init__.py", line 29
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/mail/backends'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/mail/backends/filebased.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/mail/backends/filebased.py", line 28
    except OSError, err:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/management'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/__init__.py", line 52
    except ImportError,e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/base.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/base.py", line 210
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/dumpdata.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/dumpdata.py", line 89
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/flush.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/flush.py", line 56
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/loaddata.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/loaddata.py", line 205
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/makemessages.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/makemessages.py", line 169
    print "processing language", locale
                              ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/reset.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/reset.py", line 47
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/runserver.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/runserver.py", line 47
    print "Validating models..."
                               ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/syncdb.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/commands/syncdb.py", line 40
    except ImportError, exc:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/management/sql.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/management/sql.py", line 166
    statement = re.sub(ur"--.*([\n\Z]|$)", "", statement)
                                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/serializers'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/core/servers'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/servers/basehttp.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/servers/basehttp.py", line 96
    self._headers[:] = [kv for kv in self._headers if kv[0].lower()<>name]
                                                                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/servers/fastcgi.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/servers/fastcgi.py", line 84
    print FASTCGI_HELP
                     ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/urlresolvers.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/urlresolvers.py", line 130
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/core/validators.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/core/validators.py", line 58
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/template'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/template/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/template/__init__.py", line 282
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/template/context.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/template/context.py", line 125
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/template/debug.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/template/debug.py", line 73
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/template/defaultfilters.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/template/defaultfilters.py", line 429
    starttag_re = re.compile(ur'<%s(/?>|(\s+[^>]*>))' % tags_re, re.U)
                                                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/template/defaulttags.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/template/defaulttags.py", line 307
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/template/loader.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/template/loader.py", line 96
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/template/loaders'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/template/loaders/app_directories.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/template/loaders/app_directories.py", line 22
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/templatetags'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/django/utils'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/utils/daemonize.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/utils/daemonize.py", line 6
    err_log='/dev/null', umask=022):
                                 ^
SyntaxError: invalid token

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/utils/decorators.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/utils/decorators.py", line 77
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/utils/encoding.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/utils/encoding.py", line 86
    except UnicodeDecodeError, e:
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/utils/simplejson'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/utils/simplejson/decoder.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/utils/simplejson/decoder.py", line 139
    def JSONObject((s, end), encoding, strict, scan_once, object_hook, _w=WHITESPACE.match, _ws=WHITESPACE_STR):
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/utils/simplejson/encoder.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/utils/simplejson/encoder.py", line 254
    False=False,
        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/utils/simplejson/tool.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/utils/simplejson/tool.py", line 28
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/django/utils/translation'...
Compiling './lib/python3.5/site-packages/google/appengine/_internal/django/utils/translation/trans_real.py'...
***   File "./lib/python3.5/site-packages/google/appengine/_internal/django/utils/translation/trans_real.py", line 131
    except IOError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/_internal/graphy'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/graphy/backends'...
Listing './lib/python3.5/site-packages/google/appengine/_internal/graphy/backends/google_chart_api'...
Listing './lib/python3.5/site-packages/google/appengine/api'...
Compiling './lib/python3.5/site-packages/google/appengine/api/apiproxy_rpc.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/apiproxy_rpc.py", line 132
    raise self.exception.__class__, self.exception, self._traceback
                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/apiproxy_stub_map.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/apiproxy_stub_map.py", line 330
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/app_identity'...
Compiling './lib/python3.5/site-packages/google/appengine/api/app_identity/app_identity.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/app_identity/app_identity.py", line 221
    except apiproxy_errors.ApplicationError, err:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/app_identity/app_identity_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/app_identity/app_identity_stub.py", line 46
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/backends'...
Listing './lib/python3.5/site-packages/google/appengine/api/background_thread'...
Listing './lib/python3.5/site-packages/google/appengine/api/blobstore'...
Compiling './lib/python3.5/site-packages/google/appengine/api/blobstore/blobstore.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/blobstore/blobstore.py", line 235
    except apiproxy_errors.ApplicationError, err:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/blobstore/file_blob_storage.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/blobstore/file_blob_storage.py", line 161
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/capabilities'...
Listing './lib/python3.5/site-packages/google/appengine/api/channel'...
Compiling './lib/python3.5/site-packages/google/appengine/api/channel/channel.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/channel/channel.py", line 197
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/croninfo.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/croninfo.py", line 53
    _DESCRIPTION_REGEX = ur'^.{0,499}$'
                                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/datastore.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/datastore.py", line 1149
    except (AssertionError, AttributeError, TypeError, ValueError), e:
                                                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/datastore_admin.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/datastore_admin.py", line 104
    except apiproxy_errors.ApplicationError, err:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/datastore_file_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/datastore_file_stub.py", line 356
    self.__id_counters = {datastore_stub_util.SEQUENTIAL: 1L,
                                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/datastore_types.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/datastore_types.py", line 373
    except (AssertionError, TypeError), e:
                                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/files'...
Compiling './lib/python3.5/site-packages/google/appengine/api/files/crc32c.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/files/crc32c.py", line 37
    0x00000000L, 0xf26b8303L, 0xe13b70f7L, 0x1350f3f4L,
              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/files/file.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/files/file.py", line 255
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/files/records.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/files/records.py", line 182
    return (((crc >> 15) | (crc << 17)) + _CRC_MASK_DELTA) & 0xFFFFFFFFL
                                                                       ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/images'...
Compiling './lib/python3.5/site-packages/google/appengine/api/images/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/images/__init__.py", line 886
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/labs'...
Listing './lib/python3.5/site-packages/google/appengine/api/labs/taskqueue'...
Compiling './lib/python3.5/site-packages/google/appengine/api/labs/taskqueue/taskqueue.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/labs/taskqueue/taskqueue.py", line 559
    except _RelativeUrlError, e:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/labs/taskqueue/taskqueue_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/labs/taskqueue/taskqueue_stub.py", line 524
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/lib_config.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/lib_config.py", line 166
    except ImportError, err:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/logservice'...
Compiling './lib/python3.5/site-packages/google/appengine/api/logservice/logservice.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/logservice/logservice.py", line 344
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/mail.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/mail.py", line 792
    except (Exception, Error), e:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/mail_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/mail_stub.py", line 251
    except (IOError, OSError), e:
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/memcache'...
Listing './lib/python3.5/site-packages/google/appengine/api/modules'...
Compiling './lib/python3.5/site-packages/google/appengine/api/modules/modules.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/modules/modules.py", line 139
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/namespace_manager'...
Listing './lib/python3.5/site-packages/google/appengine/api/oauth'...
Compiling './lib/python3.5/site-packages/google/appengine/api/oauth/oauth_api.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/oauth/oauth_api.py", line 140
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/prospective_search'...
Compiling './lib/python3.5/site-packages/google/appengine/api/prospective_search/prospective_search.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/prospective_search/prospective_search.py", line 350
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/remote_socket'...
Compiling './lib/python3.5/site-packages/google/appengine/api/remote_socket/_remote_socket.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/remote_socket/_remote_socket.py", line 231
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/remote_socket/_remote_socket_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/remote_socket/_remote_socket_stub.py", line 57
    except socket.gaierror, e:
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/runtime'...
Listing './lib/python3.5/site-packages/google/appengine/api/search'...
Compiling './lib/python3.5/site-packages/google/appengine/api/search/ExpressionParser.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/ExpressionParser.py", line 220
    except RecognitionException, e:
                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/search/QueryParser.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/QueryParser.py", line 282
    except RecognitionException, re:
                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/search/expression_parser.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/expression_parser.py", line 82
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/search/query_parser.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/query_parser.py", line 106
    except QueryTreeException, e:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/search/search.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/search.py", line 259
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/search/simple_search_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/simple_search_stub.py", line 253
    raise KeyError, name
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/search/stub'...
Compiling './lib/python3.5/site-packages/google/appengine/api/search/stub/document_matcher.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/stub/document_matcher.py", line 66
    raise AssertionError, 'unexpected op %s' % str(op)
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/search/stub/expression_evaluator.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/search/stub/expression_evaluator.py", line 494
    except _ExpressionError, e:
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/system'...
Listing './lib/python3.5/site-packages/google/appengine/api/taskqueue'...
Compiling './lib/python3.5/site-packages/google/appengine/api/taskqueue/taskqueue.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/taskqueue/taskqueue.py", line 904
    except _RelativeUrlError, e:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/taskqueue/taskqueue_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/taskqueue/taskqueue_stub.py", line 685
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/urlfetch.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/urlfetch.py", line 377
    except apiproxy_errors.RequestTooLargeError, err:
                                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/urlfetch_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/urlfetch_stub.py", line 130
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/users.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/users.py", line 252
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/validation.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/validation.py", line 338
    except MissingAttribute, e:
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/api/xmpp'...
Compiling './lib/python3.5/site-packages/google/appengine/api/xmpp/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/xmpp/__init__.py", line 195
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/yaml_listener.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/yaml_listener.py", line 176
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/api/yaml_object.py'...
***   File "./lib/python3.5/site-packages/google/appengine/api/yaml_object.py", line 172
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/base'...
Listing './lib/python3.5/site-packages/google/appengine/client'...
Listing './lib/python3.5/site-packages/google/appengine/client/services'...
Listing './lib/python3.5/site-packages/google/appengine/cron'...
Compiling './lib/python3.5/site-packages/google/appengine/cron/GrocParser.py'...
***   File "./lib/python3.5/site-packages/google/appengine/cron/GrocParser.py", line 260
    except RecognitionException, re:
                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/datastore'...
Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_index_xml.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_index_xml.py", line 95
    except ElementTree.ParseError, e:
                                 ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_query.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_query.py", line 1649
    except (ValueError, TypeError), e:
                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_rpc.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_rpc.py", line 385
    except KeyError, err:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_sqlite_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_sqlite_stub.py", line 627
    except sqlite3.DatabaseError, e:
                                ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_stats_generator.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_stats_generator.py", line 226
    except (AssertionError, AttributeError, TypeError, ValueError), e:
                                                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_stub_index.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_stub_index.py", line 255
    except yaml_errors.EventListenerError, e:
                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_stub_util.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_stub_util.py", line 1646
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/datastore_v4_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/datastore_v4_stub.py", line 73
    except datastore_pbs.InvalidConversionError, e:
                                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/datastore/sortable_pb_encoder.py'...
***   File "./lib/python3.5/site-packages/google/appengine/datastore/sortable_pb_encoder.py", line 81
    raise ProtocolBuffer.ProtocolBufferEncodeError, 'u16 too big'
                                                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/dist'...
Compiling './lib/python3.5/site-packages/google/appengine/dist/py_zipimport.py'...
***   File "./lib/python3.5/site-packages/google/appengine/dist/py_zipimport.py", line 134
    except (EnvironmentError, zipfile.BadZipfile), err:
                                                 ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/dist/socket.py'...
***   File "./lib/python3.5/site-packages/google/appengine/dist/socket.py", line 211
    exec _s % (_m, _m, _m, _m)
          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/dist27'...
Listing './lib/python3.5/site-packages/google/appengine/dist27/gae_override'...
Compiling './lib/python3.5/site-packages/google/appengine/dist27/gae_override/httplib.py'...
***   File "./lib/python3.5/site-packages/google/appengine/dist27/gae_override/httplib.py", line 521
    except urlfetch.InvalidURLError, e:
                                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/dist27/python_std_lib'...
Compiling './lib/python3.5/site-packages/google/appengine/dist27/python_std_lib/httplib.py'...
***   File "./lib/python3.5/site-packages/google/appengine/dist27/python_std_lib/httplib.py", line 369
    print "reply:", repr(line)
                 ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/dist27/socket.py'...
***   File "./lib/python3.5/site-packages/google/appengine/dist27/socket.py", line 350
    except error, e:
                ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/dist27/threading.py'...
***   File "./lib/python3.5/site-packages/google/appengine/dist27/threading.py", line 360
    raise ValueError, "Semaphore released too many times"
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/dist27/urllib.py'...
***   File "./lib/python3.5/site-packages/google/appengine/dist27/urllib.py", line 206
    except socket.error, msg:
                       ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext'...
Listing './lib/python3.5/site-packages/google/appengine/ext/admin'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/admin/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/admin/__init__.py", line 201
    except IOError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/admin/templates'...
Listing './lib/python3.5/site-packages/google/appengine/ext/admin/templates/css'...
Listing './lib/python3.5/site-packages/google/appengine/ext/admin/templates/images'...
Listing './lib/python3.5/site-packages/google/appengine/ext/admin/templates/js'...
Listing './lib/python3.5/site-packages/google/appengine/ext/admin_redirect'...
Listing './lib/python3.5/site-packages/google/appengine/ext/analytics'...
Listing './lib/python3.5/site-packages/google/appengine/ext/analytics/static'...
Listing './lib/python3.5/site-packages/google/appengine/ext/analytics/templates'...
Listing './lib/python3.5/site-packages/google/appengine/ext/appstats'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/appstats/formatting.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/appstats/formatting.py", line 87
    if val >= 10L**99:
                ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/appstats/recording.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/appstats/recording.py", line 1149
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/appstats/static'...
Listing './lib/python3.5/site-packages/google/appengine/ext/appstats/templates'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/appstats/ui.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/appstats/ui.py", line 103
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/blobstore'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/blobstore/blobstore.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/blobstore/blobstore.py", line 476
    except blobstore._CreationFormatError, err:
                                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/builtins'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/admin_redirect'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/appstats'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/datastore_admin'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/default'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/deferred'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/django_wsgi'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/mapreduce'...
Listing './lib/python3.5/site-packages/google/appengine/ext/builtins/remote_api'...
Listing './lib/python3.5/site-packages/google/appengine/ext/bulkload'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/bulkload/bulkloader_config.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/bulkload/bulkloader_config.py", line 289
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/bulkload/bulkloader_parser.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/bulkload/bulkloader_parser.py", line 86
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/cloudstorage'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/cloudstorage/stub_dispatcher.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/cloudstorage/stub_dispatcher.py", line 190
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/datastore_admin'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/backup_handler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/datastore_admin/backup_handler.py", line 308
    except Exception, ex:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/copy_handler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/datastore_admin/copy_handler.py", line 182
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/delete_handler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/datastore_admin/delete_handler.py", line 197
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/main.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/datastore_admin/main.py", line 163
    except datastore_errors.Error, e:
                                 ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/remote_api_put_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/datastore_admin/remote_api_put_stub.py", line 142
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/static'...
Listing './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/static/css'...
Listing './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/static/img'...
Listing './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/static/img/icn'...
Listing './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/static/js'...
Listing './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/templates'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/datastore_admin/utils.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/datastore_admin/utils.py", line 599
    except BaseException, ex:
                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/db'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/db/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/db/__init__.py", line 1268
    except BadKeyError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/db/djangoforms.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/db/djangoforms.py", line 680
    except (db.BadValueError, ValueError), e:
                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/db/stats.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/db/stats.py", line 85
    entity_bytes = db.IntegerProperty(default=0L)
                                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/deferred'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/deferred/deferred.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/deferred/deferred.py", line 144
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/django'...
Listing './lib/python3.5/site-packages/google/appengine/ext/django/backends'...
Listing './lib/python3.5/site-packages/google/appengine/ext/django/backends/rdbms'...
Listing './lib/python3.5/site-packages/google/appengine/ext/django/management'...
Listing './lib/python3.5/site-packages/google/appengine/ext/django/management/commands'...
Listing './lib/python3.5/site-packages/google/appengine/ext/endpoints'...
Listing './lib/python3.5/site-packages/google/appengine/ext/ereporter'...
Listing './lib/python3.5/site-packages/google/appengine/ext/ereporter/templates'...
Listing './lib/python3.5/site-packages/google/appengine/ext/gql'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/gql/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/gql/__init__.py", line 274
    except datastore_errors.BadQueryError, error:
                                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/key_range'...
Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce'...
Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce/api'...
Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce/api/map_job'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/api/map_job/abstract_datastore_input_reader.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/api/map_job/abstract_datastore_input_reader.py", line 292
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/api/map_job/model_datastore_input_reader.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/api/map_job/model_datastore_input_reader.py", line 109
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/base_handler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/base_handler.py", line 234
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/context.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/context.py", line 173
    except db.Timeout, e:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/handlers.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/handlers.py", line 380
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/input_readers.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/input_readers.py", line 371
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce/lib'...
Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce/lib/input_reader'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/lib/input_reader/_gcs.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/lib/input_reader/_gcs.py", line 186
    except ValueError, error:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/mapreduce_pipeline.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/mapreduce_pipeline.py", line 222
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce/operation'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/output_writers.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/output_writers.py", line 1041
    except ValueError, error:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/property_range.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/property_range.py", line 298
    except UnicodeEncodeError, e:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/records.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/records.py", line 135
    return (((crc >> 15) | (crc << 17)) + _CRC_MASK_DELTA) & 0xFFFFFFFFL
                                                                       ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce/static'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/status.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/status.py", line 239
    except (ValueError, yaml_errors.EventError), e:
                                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/mapreduce/test_support.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/mapreduce/test_support.py", line 214
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/mapreduce/tools'...
Listing './lib/python3.5/site-packages/google/appengine/ext/ndb'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/ndb/blobstore.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/ndb/blobstore.py", line 376
    except blobstore._CreationFormatError, err:
                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/ndb/context.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/ndb/context.py", line 893
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/ndb/key.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/ndb/key.py", line 85
    _MAX_LONG = 2L ** 63  # Use 2L, see issue 65.  http://goo.gl/ELczz
                 ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/ndb/query.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/ndb/query.py", line 1382
    except TypeError, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/ndb/stats.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/ndb/stats.py", line 81
    entity_bytes = model.IntegerProperty(default=0L)
                                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/ndb/tasklets.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/ndb/tasklets.py", line 322
    raise self._exception.__class__, self._exception, self._traceback
                                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/preload'...
Listing './lib/python3.5/site-packages/google/appengine/ext/remote_api'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/remote_api/handler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/remote_api/handler.py", line 407
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/remote_api/remote_api_stub.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/remote_api/remote_api_stub.py", line 707
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/search'...
Listing './lib/python3.5/site-packages/google/appengine/ext/testbed'...
Listing './lib/python3.5/site-packages/google/appengine/ext/vendor'...
Listing './lib/python3.5/site-packages/google/appengine/ext/webapp'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/webapp/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/webapp/__init__.py", line 164
    except (ImportError, EnvironmentError), e:
                                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/webapp/_webapp25.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/webapp/_webapp25.py", line 310
    except UnicodeError, e:
                       ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/webapp/mail_handlers.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/webapp/mail_handlers.py", line 173
    except KeyError, e:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/webapp/util.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/webapp/util.py", line 131
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/ext/webapp/xmpp_handlers.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/webapp/xmpp_handlers.py", line 70
    except xmpp.InvalidMessageError, e:
                                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/ext/zipserve'...
Compiling './lib/python3.5/site-packages/google/appengine/ext/zipserve/__init__.py'...
***   File "./lib/python3.5/site-packages/google/appengine/ext/zipserve/__init__.py", line 132
    except (IOError, RuntimeError, zipfile.BadZipfile), err:
                                                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/runtime'...
Compiling './lib/python3.5/site-packages/google/appengine/runtime/apiproxy.py'...
***   File "./lib/python3.5/site-packages/google/appengine/runtime/apiproxy.py", line 167
    raise new_exc.__class__, new_exc, tb
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/tools'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/api_server.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/api_server.py", line 91
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/appcfg.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/appcfg.py", line 457
    except urllib2.HTTPError, err:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/appengine_rpc.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/appengine_rpc.py", line 258
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/appengine_rpc_httplib2.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/appengine_rpc_httplib2.py", line 229
    except client.AccessTokenRefreshError, e:
                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/backends_conversion.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/backends_conversion.py", line 125
    print 'File %s not written.' % (filename,)
                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/bulkload_client.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/bulkload_client.py", line 155
    except (IOError, httplib.HTTPException, socket.error), e:
                                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/bulkloader.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/bulkloader.py", line 586
    except csv.Error, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/dev_appserver.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/dev_appserver.py", line 579
    except re.error, e:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/dev_appserver_apiserver.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/dev_appserver_apiserver.py", line 459
    except ValueError, unused_err:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/dev_appserver_blobimage.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/dev_appserver_blobimage.py", line 162
    raise ValueError, 'Invalid resize'
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/dev_appserver_blobstore.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/dev_appserver_blobstore.py", line 393
    except dev_appserver_upload.FilenameOrContentTypeTooLargeError, ex:
                                                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/dev_appserver_import_hook.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/dev_appserver_import_hook.py", line 105
    def FakeOpen(filename, flags, mode=0777):
                                          ^
SyntaxError: invalid token

Compiling './lib/python3.5/site-packages/google/appengine/tools/dev_appserver_main.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/dev_appserver_main.py", line 365
    print sys.modules['__main__'].__doc__ % render_dict
            ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/google/appengine/tools/dev_appserver_multiprocess.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/dev_appserver_multiprocess.py", line 256
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2'...
Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2/admin'...
Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2/admin/assets'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/admin/console.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/admin/console.py", line 52
    except module.InteractiveCommandError, e:
                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/admin/logs_handler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/admin/logs_handler.py", line 36
    except KeyError, e:
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2/admin/templates'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/api_server.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/api_server.py", line 198
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/application_configuration.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/application_configuration.py", line 285
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/blob_upload.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/blob_upload.py", line 374
    except _InvalidMIMETypeFormatError, ex:
                                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/blob_upload_test.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/blob_upload_test.py", line 1046
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/devappserver2.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/devappserver2.py", line 102
    os.mkdir(path, 0700)
                      ^
SyntaxError: invalid token

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/devappserver2_test.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/devappserver2_test.py", line 117
    os.chmod(path1, 0777)
                       ^
SyntaxError: invalid token

Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2/endpoints'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/endpoints/api_config_manager.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/endpoints/api_config_manager.py", line 94
    except ValueError, unused_err:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2/endpoints/testdata'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/health_check_service.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/health_check_service.py", line 155
    except request_info.Error, e:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/module.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/module.py", line 154
    except re.error, e:
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2/php'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/php/runtime.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/php/runtime.py", line 224
    print server.port
               ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/google/appengine/tools/devappserver2/python'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/python/runtime.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/python/runtime.py", line 143
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/python/stubs.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/python/stubs.py", line 68
    def fake_open(filename, flags, mode=0777, _os_open=os.open):
                                           ^
SyntaxError: invalid token

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/request_rewriter.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/request_rewriter.py", line 305
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/request_rewriter_test.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/request_rewriter_test.py", line 201
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/static_files_handler.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/static_files_handler.py", line 295
    except re.error, e:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/vm_runtime_proxy_go.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/vm_runtime_proxy_go.py", line 290
    os.chmod(dst_build, 0777)
                           ^
SyntaxError: invalid token

Compiling './lib/python3.5/site-packages/google/appengine/tools/devappserver2/win32_file_watcher.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/devappserver2/win32_file_watcher.py", line 34
    WAIT_OBJECT_0 = 0x00000000L
                              ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/appengine/tools/docker'...
Compiling './lib/python3.5/site-packages/google/appengine/tools/download_appstats.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/download_appstats.py", line 64
    except ImportError, err:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/endpointscfg.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/endpointscfg.py", line 276
    except urllib2.HTTPError, error:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/gen_protorpc.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/gen_protorpc.py", line 74
    except IOError, err:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/requeue.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/requeue.py", line 112
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/appengine/tools/sdk_update_checker.py'...
***   File "./lib/python3.5/site-packages/google/appengine/tools/sdk_update_checker.py", line 244
    except (urllib2.URLError, socket.error, ssl.SSLError), e:
                                                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/net'...
Listing './lib/python3.5/site-packages/google/net/proto'...
Compiling './lib/python3.5/site-packages/google/net/proto/ProtocolBuffer.py'...
***   File "./lib/python3.5/site-packages/google/net/proto/ProtocolBuffer.py", line 155
    raise ProtocolBufferDecodeError, '\n\t'.join(dbg)
                                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/net/proto2'...
Listing './lib/python3.5/site-packages/google/net/proto2/proto'...
Listing './lib/python3.5/site-packages/google/net/proto2/python'...
Listing './lib/python3.5/site-packages/google/net/proto2/python/internal'...
Compiling './lib/python3.5/site-packages/google/net/proto2/python/internal/decoder.py'...
***   File "./lib/python3.5/site-packages/google/net/proto2/python/internal/decoder.py", line 474
    except UnicodeDecodeError, e:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/net/proto2/python/internal/python_message.py'...
***   File "./lib/python3.5/site-packages/google/net/proto2/python/internal/python_message.py", line 303
    raise type(exc), exc, sys.exc_info()[2]
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/net/proto2/python/public'...
Compiling './lib/python3.5/site-packages/google/net/proto2/python/public/text_format.py'...
***   File "./lib/python3.5/site-packages/google/net/proto2/python/public/text_format.py", line 564
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/pyglib'...
Listing './lib/python3.5/site-packages/google/storage'...
Listing './lib/python3.5/site-packages/google/storage/speckle'...
Listing './lib/python3.5/site-packages/google/storage/speckle/proto'...
Listing './lib/python3.5/site-packages/google/storage/speckle/python'...
Listing './lib/python3.5/site-packages/google/storage/speckle/python/api'...
Listing './lib/python3.5/site-packages/google/storage/speckle/python/api/constants'...
Compiling './lib/python3.5/site-packages/google/storage/speckle/python/api/rdbms_apiproxy.py'...
***   File "./lib/python3.5/site-packages/google/storage/speckle/python/api/rdbms_apiproxy.py", line 68
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/google/storage/speckle/python/api/rdbms_googleapi.py'...
***   File "./lib/python3.5/site-packages/google/storage/speckle/python/api/rdbms_googleapi.py", line 212
    except (errors.Error, client.Error, httplib2.HttpLib2Error), e:
                                                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/google/storage/speckle/python/django'...
Listing './lib/python3.5/site-packages/google/storage/speckle/python/django/backend'...
Listing './lib/python3.5/site-packages/google/storage/speckle/python/django/management'...
Listing './lib/python3.5/site-packages/google/storage/speckle/python/django/management/commands'...
Listing './lib/python3.5/site-packages/google/storage/speckle/python/tool'...
Compiling './lib/python3.5/site-packages/google/storage/speckle/python/tool/google_sql.py'...
***   File "./lib/python3.5/site-packages/google/storage/speckle/python/tool/google_sql.py", line 194
    print output.encode(self.output_encoding)
               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pip'...
Listing './lib/python3.5/site-packages/pip/_vendor'...
Listing './lib/python3.5/site-packages/pip/commands'...
Listing './lib/python3.5/site-packages/pip/compat'...
Listing './lib/python3.5/site-packages/pip/models'...
Listing './lib/python3.5/site-packages/pip/operations'...
Listing './lib/python3.5/site-packages/pip/req'...
Listing './lib/python3.5/site-packages/pip/utils'...
Listing './lib/python3.5/site-packages/pip/vcs'...
Listing './lib/python3.5/site-packages/pip-9.0.1.dist-info'...
Listing './lib/python3.5/site-packages/pkg_resources'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor/packaging'...
Listing './lib/python3.5/site-packages/pkg_resources/extern'...
Listing './lib/python3.5/site-packages/pkg_resources-0.0.0.dist-info'...
Listing './lib/python3.5/site-packages/python_appengine-1.9.15.egg-info'...
Listing './lib/python3.5/site-packages/setuptools'...
Listing './lib/python3.5/site-packages/setuptools/command'...
Listing './lib/python3.5/site-packages/setuptools/extern'...
Listing './lib/python3.5/site-packages/setuptools-32.3.1.dist-info'...
Listing './share'...
Listing './share/python-wheels'...
