Listing '.'...
Listing './bin'...
Listing './include'...
Listing './lib'...
Listing './lib/python3.5'...
Listing './lib/python3.5/site-packages'...
Listing './lib/python3.5/site-packages/GitPython-2.1.8.dist-info'...
Listing './lib/python3.5/site-packages/PyYAML-3.12.egg-info'...
Listing './lib/python3.5/site-packages/_pytest'...
Listing './lib/python3.5/site-packages/_pytest/_code'...
Listing './lib/python3.5/site-packages/_pytest/assertion'...
Listing './lib/python3.5/site-packages/_pytest/vendored_packages'...
Listing './lib/python3.5/site-packages/astroid'...
Listing './lib/python3.5/site-packages/astroid/brain'...
Listing './lib/python3.5/site-packages/astroid/tests'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/SSL1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/absimp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/absimp/sidepackage'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/all.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/all.py", line 7
    def func(): print 'yo'
                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/appl'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/find_test'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/lmfp'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module.py", line 32
    except ValueError, ex:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module1abs'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module2.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module2.py", line 78
    exec 'c = 3'
               ^
SyntaxError: Missing parentheses in call to 'exec'

Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/noendingnewline.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/noendingnewline.py", line 21
    print 'a'
            ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/package/subpackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/unicode_package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/unicode_package/core'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/SSL1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/absimp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/absimp/sidepackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/appl'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/find_test'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/lmfp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/module1abs'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/package/subpackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/unicode_package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/unicode_package/core'...
Listing './lib/python3.5/site-packages/astroid-1.4.9.dist-info'...
Listing './lib/python3.5/site-packages/bandit'...
Listing './lib/python3.5/site-packages/bandit/blacklists'...
Listing './lib/python3.5/site-packages/bandit/cli'...
Listing './lib/python3.5/site-packages/bandit/core'...
Listing './lib/python3.5/site-packages/bandit/formatters'...
Listing './lib/python3.5/site-packages/bandit/plugins'...
Listing './lib/python3.5/site-packages/bandit-1.4.0.dist-info'...
Listing './lib/python3.5/site-packages/coverage'...
Listing './lib/python3.5/site-packages/coverage/htmlfiles'...
Listing './lib/python3.5/site-packages/coverage-4.3.4.dist-info'...
Listing './lib/python3.5/site-packages/files_by_date'...
Listing './lib/python3.5/site-packages/files_by_date/app'...
Listing './lib/python3.5/site-packages/files_by_date/parsers'...
Listing './lib/python3.5/site-packages/files_by_date/service'...
Listing './lib/python3.5/site-packages/files_by_date/utils'...
Listing './lib/python3.5/site-packages/files_by_date/validators'...
Listing './lib/python3.5/site-packages/files_by_date-1.0.0.egg-info'...
Listing './lib/python3.5/site-packages/git'...
Listing './lib/python3.5/site-packages/git/index'...
Listing './lib/python3.5/site-packages/git/objects'...
Listing './lib/python3.5/site-packages/git/objects/submodule'...
Listing './lib/python3.5/site-packages/git/refs'...
Listing './lib/python3.5/site-packages/git/repo'...
Listing './lib/python3.5/site-packages/git/test'...
Listing './lib/python3.5/site-packages/git/test/fixtures'...
Listing './lib/python3.5/site-packages/git/test/lib'...
Listing './lib/python3.5/site-packages/git/test/performance'...
Listing './lib/python3.5/site-packages/gitdb'...
Listing './lib/python3.5/site-packages/gitdb/db'...
Listing './lib/python3.5/site-packages/gitdb/test'...
Listing './lib/python3.5/site-packages/gitdb/utils'...
Listing './lib/python3.5/site-packages/gitdb2-2.0.3.dist-info'...
Listing './lib/python3.5/site-packages/isort'...
Listing './lib/python3.5/site-packages/isort-4.2.15.dist-info'...
Listing './lib/python3.5/site-packages/lazy_object_proxy'...
Listing './lib/python3.5/site-packages/lazy_object_proxy-1.3.1.dist-info'...
Listing './lib/python3.5/site-packages/mccabe-0.6.1.dist-info'...
Listing './lib/python3.5/site-packages/pbr'...
Listing './lib/python3.5/site-packages/pbr/cmd'...
Listing './lib/python3.5/site-packages/pbr/hooks'...
Listing './lib/python3.5/site-packages/pbr/tests'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/data_files'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/doc'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/doc/source'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/pbr_testpackage'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/pbr_testpackage/package_data'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/src'...
Listing './lib/python3.5/site-packages/pbr-3.1.1.dist-info'...
Listing './lib/python3.5/site-packages/pip'...
Listing './lib/python3.5/site-packages/pip/_vendor'...
Listing './lib/python3.5/site-packages/pip/commands'...
Listing './lib/python3.5/site-packages/pip/compat'...
Listing './lib/python3.5/site-packages/pip/models'...
Listing './lib/python3.5/site-packages/pip/operations'...
Listing './lib/python3.5/site-packages/pip/req'...
Listing './lib/python3.5/site-packages/pip/utils'...
Listing './lib/python3.5/site-packages/pip/vcs'...
Listing './lib/python3.5/site-packages/pip-9.0.1.dist-info'...
Listing './lib/python3.5/site-packages/pkg_resources'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor/packaging'...
Listing './lib/python3.5/site-packages/pkg_resources/extern'...
Listing './lib/python3.5/site-packages/pkg_resources-0.0.0.dist-info'...
Listing './lib/python3.5/site-packages/pluggy'...
Listing './lib/python3.5/site-packages/pluggy-0.6.0.egg-info'...
Listing './lib/python3.5/site-packages/py'...
Listing './lib/python3.5/site-packages/py/_code'...
Listing './lib/python3.5/site-packages/py/_io'...
Listing './lib/python3.5/site-packages/py/_log'...
Listing './lib/python3.5/site-packages/py/_path'...
Listing './lib/python3.5/site-packages/py/_process'...
Listing './lib/python3.5/site-packages/py/_vendored_packages'...
Listing './lib/python3.5/site-packages/py-1.5.2.dist-info'...
Listing './lib/python3.5/site-packages/pylint'...
Listing './lib/python3.5/site-packages/pylint/checkers'...
Listing './lib/python3.5/site-packages/pylint/extensions'...
Listing './lib/python3.5/site-packages/pylint/pyreverse'...
Listing './lib/python3.5/site-packages/pylint/reporters'...
Listing './lib/python3.5/site-packages/pylint/reporters/ureports'...
Listing './lib/python3.5/site-packages/pylint/test'...
Listing './lib/python3.5/site-packages/pylint/test/data'...
Listing './lib/python3.5/site-packages/pylint/test/extensions'...
Listing './lib/python3.5/site-packages/pylint/test/extensions/data'...
Listing './lib/python3.5/site-packages/pylint/test/functional'...
Compiling './lib/python3.5/site-packages/pylint/test/functional/anomalous_unicode_escape_py2.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/anomalous_unicode_escape_py2.py", line 17
    RAW_UNICODE = ur"\u0062\n"
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/async_functions.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/async_functions.py", line 57
    async def func(a, a, b=[]):
         ^
SyntaxError: duplicate argument 'a' in function definition

Compiling './lib/python3.5/site-packages/pylint/test/functional/class_members_py27.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/class_members_py27.py", line 24
    print self.nonexistent
             ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/continue_in_finally.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/continue_in_finally.py", line 9
    continue # [continue-in-finally]
    ^
SyntaxError: 'continue' not supported inside 'finally' clause

Compiling './lib/python3.5/site-packages/pylint/test/functional/duplicate_argument_name.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/duplicate_argument_name.py", line 4
    def foo1(_, _): # [duplicate-argument-name]
                                              ^
SyntaxError: duplicate argument '_' in function definition

Compiling './lib/python3.5/site-packages/pylint/test/functional/exec_used_py2.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/exec_used_py2.py", line 3
    exec 'a = __revision__' # [exec-used]
                          ^
SyntaxError: Missing parentheses in call to 'exec'

Compiling './lib/python3.5/site-packages/pylint/test/functional/invalid_star_assignment_target.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/invalid_star_assignment_target.py", line 3
    *FIRST = [1, 2, 3] # [invalid-star-assignment-target]
                                                        ^
SyntaxError: starred assignment target must be in a list or tuple

Compiling './lib/python3.5/site-packages/pylint/test/functional/iterable_context_py2.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/iterable_context_py2.py", line 16
    print i
          ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/misplaced_future.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/misplaced_future.py", line 3
    from __future__ import print_function # [misplaced-future]
                                                             ^
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling './lib/python3.5/site-packages/pylint/test/functional/nonlocal_and_global.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/nonlocal_and_global.py", line 5
    nonlocal missing
    ^
SyntaxError: name 'missing' is nonlocal and global

Compiling './lib/python3.5/site-packages/pylint/test/functional/nonlocal_without_binding.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/nonlocal_without_binding.py", line 22
    nonlocal b  # [nonlocal-without-binding]
    ^
SyntaxError: no binding for nonlocal 'b' found

Compiling './lib/python3.5/site-packages/pylint/test/functional/not_in_loop.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/not_in_loop.py", line 7
    continue # [not-in-loop]
    ^
SyntaxError: 'continue' not properly in loop

Compiling './lib/python3.5/site-packages/pylint/test/functional/old_division_manually.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/old_division_manually.py", line 2
    print 1 / 3
          ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/pygtk_enum_crash.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/pygtk_enum_crash.py", line 10
    print arg
            ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/pygtk_import.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/pygtk_import.py", line 11
    print self
             ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/return_outside_function.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/return_outside_function.py", line 2
    return # [return-outside-function]
                                     ^
SyntaxError: 'return' outside function

Compiling './lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target.py", line 3
    FIRST = *[1, 2]  # [star-needs-assignment-target]
           ^
SyntaxError: can't use starred expression here

Compiling './lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target_py35.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target_py35.py", line 15
    UNPACK_IN_COMP = {elem for elem in (*range(10))} # [star-needs-assignment-target]
                                       ^
SyntaxError: can't use starred expression here

Compiling './lib/python3.5/site-packages/pylint/test/functional/syntax_error.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/syntax_error.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/syntax_error_jython.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/syntax_error_jython.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/too_many_star_expressions.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/too_many_star_expressions.py", line 3
    *FIRST, *SECOND = [1, 2, 3] # [too-many-star-expressions]
                                                            ^
SyntaxError: two starred expressions in assignment

Compiling './lib/python3.5/site-packages/pylint/test/functional/unpacked_exceptions.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/unpacked_exceptions.py", line 7
    except IOError, (errno, message):  # [unpacking-in-except]
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_from_outside_func.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_from_outside_func.py", line 2
    yield from [1, 2]  # [yield-outside-function]
                                                ^
SyntaxError: 'yield' outside function

Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_inside_async_function.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_inside_async_function.py", line 11
    yield 42 # [yield-inside-async-function]
    ^
SyntaxError: 'yield' inside async function

Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_outside_func.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_outside_func.py", line 2
    yield 1  # [yield-outside-function]
                                      ^
SyntaxError: 'yield' outside function

Listing './lib/python3.5/site-packages/pylint/test/input'...
Compiling './lib/python3.5/site-packages/pylint/test/input/func_w0122_py_30.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_w0122_py_30.py", line 5
    exec 'a = __revision__'
                          ^
SyntaxError: Missing parentheses in call to 'exec'

Compiling './lib/python3.5/site-packages/pylint/test/input/func_w0332_py_30.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_w0332_py_30.py", line 4
    __revision__ = 1l
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint/test/input/func_w0401_package'...
Compiling './lib/python3.5/site-packages/pylint/test/input/func_w0623_py_30.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_w0623_py_30.py", line 18
    except KeyError, exceptions.RuntimeError: # W0623
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/input/func_w0705.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_w0705.py", line 28
    __revision__ += 1
                   ^
SyntaxError: default 'except:' must be last

Compiling './lib/python3.5/site-packages/pylint/test/input/syntax_error.py'...
*** Sorry: IndentationError: expected an indented block (syntax_error.py, line 2)
Listing './lib/python3.5/site-packages/pylint/test/messages'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/absimp'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/bad_package'...
Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/bad_package/__init__.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/bad_package/__init__.py", line 2
    raise missing.Missing..
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/descriptor_crash.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/descriptor_crash.py", line 20
    print p.getPage(sys.argv[1])
          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/dummy'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package/subpackage'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package_all'...
Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/py3k_error_flag.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/py3k_error_flag.py", line 4
    raise Exception, 1  # Error emitted here with the Python 3 checker.
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/syntax_error.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/syntax_error.py", line 1
    class A extends B {}
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint-1.6.5.dist-info'...
Listing './lib/python3.5/site-packages/pytest-3.0.6.dist-info'...
Listing './lib/python3.5/site-packages/setuptools'...
Listing './lib/python3.5/site-packages/setuptools/command'...
Listing './lib/python3.5/site-packages/setuptools/extern'...
Listing './lib/python3.5/site-packages/setuptools-32.3.1.dist-info'...
Listing './lib/python3.5/site-packages/six-1.11.0.dist-info'...
Listing './lib/python3.5/site-packages/smmap'...
Listing './lib/python3.5/site-packages/smmap/test'...
Listing './lib/python3.5/site-packages/smmap2-2.0.3.dist-info'...
Listing './lib/python3.5/site-packages/stevedore'...
Listing './lib/python3.5/site-packages/stevedore/example'...
Listing './lib/python3.5/site-packages/stevedore/example2'...
Listing './lib/python3.5/site-packages/stevedore/tests'...
Listing './lib/python3.5/site-packages/stevedore-1.28.0.dist-info'...
Listing './lib/python3.5/site-packages/test'...
Listing './lib/python3.5/site-packages/test/integration_test'...
Listing './lib/python3.5/site-packages/test/unit_test'...
Listing './lib/python3.5/site-packages/tox'...
Listing './lib/python3.5/site-packages/tox-2.6.0.dist-info'...
Listing './lib/python3.5/site-packages/virtualenv-15.1.0.dist-info'...
Listing './lib/python3.5/site-packages/virtualenv_support'...
Listing './lib/python3.5/site-packages/wrapt'...
Listing './lib/python3.5/site-packages/wrapt-1.10.11.egg-info'...
Listing './lib/python3.5/site-packages/yaml'...
Listing './share'...
Listing './share/python-wheels'...
