Listing '.'...
Listing './bin'...
Compiling './bin/appcfg.py'...
Compiling './bin/bulkload_client.py'...
Compiling './bin/bulkloader.py'...
Compiling './bin/dev_appserver.py'...
Compiling './bin/gae-manage.py'...
***   File "./bin/gae-manage.py", line 55
    print '%s project already exists' % project_name
                                    ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './bin/gen_protorpc.py'...
Compiling './bin/remote_api_shell.py'...
Listing './include'...
Listing './lib'...
Listing './lib/python3.5'...
Listing './lib/python3.5/site-packages'...
Listing './lib/python3.5/site-packages/apps'...
Listing './lib/python3.5/site-packages/apps/admin'...
Listing './lib/python3.5/site-packages/apps/admin/static'...
Listing './lib/python3.5/site-packages/apps/admin/static/css'...
Listing './lib/python3.5/site-packages/apps/admin/static/img'...
Listing './lib/python3.5/site-packages/apps/admin/static/js'...
Listing './lib/python3.5/site-packages/apps/admin/templates'...
Listing './lib/python3.5/site-packages/apps/admin/translate'...
Listing './lib/python3.5/site-packages/apps/api'...
Listing './lib/python3.5/site-packages/apps/banner'...
Listing './lib/python3.5/site-packages/apps/banner/translate'...
Listing './lib/python3.5/site-packages/apps/blog'...
Listing './lib/python3.5/site-packages/apps/blog/static'...
Listing './lib/python3.5/site-packages/apps/blog/static/css'...
Listing './lib/python3.5/site-packages/apps/blog/templates'...
Listing './lib/python3.5/site-packages/apps/blog/templates/block'...
Listing './lib/python3.5/site-packages/apps/blog/translate'...
Listing './lib/python3.5/site-packages/apps/blogs'...
Listing './lib/python3.5/site-packages/apps/blogs/static'...
Listing './lib/python3.5/site-packages/apps/blogs/static/css'...
Listing './lib/python3.5/site-packages/apps/blogs/templates'...
Listing './lib/python3.5/site-packages/apps/blogs/templates/block'...
Listing './lib/python3.5/site-packages/apps/blogs/translate'...
Listing './lib/python3.5/site-packages/apps/comments'...
Listing './lib/python3.5/site-packages/apps/comments/static'...
Listing './lib/python3.5/site-packages/apps/comments/static/css'...
Listing './lib/python3.5/site-packages/apps/comments/templates'...
Listing './lib/python3.5/site-packages/apps/comments/templates/block'...
Listing './lib/python3.5/site-packages/apps/comments/translate'...
Listing './lib/python3.5/site-packages/apps/guestbook'...
Listing './lib/python3.5/site-packages/apps/guestbook/templates'...
Listing './lib/python3.5/site-packages/apps/guestbook/translate'...
Listing './lib/python3.5/site-packages/apps/images'...
Listing './lib/python3.5/site-packages/apps/location'...
Listing './lib/python3.5/site-packages/apps/location/templates'...
Listing './lib/python3.5/site-packages/apps/message'...
Listing './lib/python3.5/site-packages/apps/pages'...
Compiling './lib/python3.5/site-packages/apps/pages/controllers.py'...
***   File "./lib/python3.5/site-packages/apps/pages/controllers.py", line 6
    except TemplateDoesNotExist, err:
                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/apps/todo'...
Listing './lib/python3.5/site-packages/apps/todo/static'...
Listing './lib/python3.5/site-packages/apps/todo/static/css'...
Listing './lib/python3.5/site-packages/apps/todo/templates'...
Listing './lib/python3.5/site-packages/apps/todo/translate'...
Listing './lib/python3.5/site-packages/apps/user'...
Listing './lib/python3.5/site-packages/apps/user/static'...
Listing './lib/python3.5/site-packages/apps/user/static/css'...
Listing './lib/python3.5/site-packages/apps/user/static/js'...
Listing './lib/python3.5/site-packages/apps/user/templates'...
Listing './lib/python3.5/site-packages/apps/user/templates/block'...
Listing './lib/python3.5/site-packages/apps/user/translate'...
Listing './lib/python3.5/site-packages/gae'...
Compiling './lib/python3.5/site-packages/gae/config.py'...
***   File "./lib/python3.5/site-packages/gae/config.py", line 24
    raise Exception, "For access to configuration please use get_config() function"
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/gae/db'...
Compiling './lib/python3.5/site-packages/gae/db/__init__.py'...
***   File "./lib/python3.5/site-packages/gae/db/__init__.py", line 67
    raise RuntimeError, "Missing keys required by %s entity's "\
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/gae/forms'...
Listing './lib/python3.5/site-packages/gae/sceleton'...
Listing './lib/python3.5/site-packages/gae/sceleton/app'...
Listing './lib/python3.5/site-packages/gae/sceleton/app/static'...
Listing './lib/python3.5/site-packages/gae/sceleton/app/static/css'...
Listing './lib/python3.5/site-packages/gae/sceleton/app/static/js'...
Listing './lib/python3.5/site-packages/gae/sceleton/app/templates'...
Listing './lib/python3.5/site-packages/gae/sceleton/app/translate'...
Listing './lib/python3.5/site-packages/gae/sceleton/project'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site/static'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site/static/css'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site/static/img'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site/static/js'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site/templates'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site/templates/common'...
Listing './lib/python3.5/site-packages/gae/sceleton/project/apps/site/translate'...
Listing './lib/python3.5/site-packages/gae/sessions'...
Compiling './lib/python3.5/site-packages/gae/sessions/__init__.py'...
***   File "./lib/python3.5/site-packages/gae/sessions/__init__.py", line 321
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/gae/tags.py'...
***   File "./lib/python3.5/site-packages/gae/tags.py", line 89
    except (AttributeError, VariableDoesNotExist), err:
                                                 ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/gae/template'...
Compiling './lib/python3.5/site-packages/gae/template/__init__.py'...
***   File "./lib/python3.5/site-packages/gae/template/__init__.py", line 17
    except (EnvironmentError, RuntimeError), e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/gae/template/loader.py'...
***   File "./lib/python3.5/site-packages/gae/template/loader.py", line 35
    raise TemplateDoesNotExist, "Not specified application prefix in '%s' template path" % template_name
                              ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/gae/tools'...
Compiling './lib/python3.5/site-packages/gae/webapp.py'...
***   File "./lib/python3.5/site-packages/gae/webapp.py", line 276
    except Request.REDIRECT, err:
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/gaeframework-2.0.10.egg-info'...
Listing './lib/python3.5/site-packages/pip'...
Listing './lib/python3.5/site-packages/pip/_vendor'...
Listing './lib/python3.5/site-packages/pip/commands'...
Listing './lib/python3.5/site-packages/pip/compat'...
Listing './lib/python3.5/site-packages/pip/models'...
Listing './lib/python3.5/site-packages/pip/operations'...
Listing './lib/python3.5/site-packages/pip/req'...
Listing './lib/python3.5/site-packages/pip/utils'...
Listing './lib/python3.5/site-packages/pip/vcs'...
Listing './lib/python3.5/site-packages/pip-9.0.1.dist-info'...
Listing './lib/python3.5/site-packages/pkg_resources'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor/packaging'...
Listing './lib/python3.5/site-packages/pkg_resources/extern'...
Listing './lib/python3.5/site-packages/pkg_resources-0.0.0.dist-info'...
Listing './lib/python3.5/site-packages/project1'...
Listing './lib/python3.5/site-packages/project1/blog'...
Listing './lib/python3.5/site-packages/project1/gae'...
Compiling './lib/python3.5/site-packages/project1/gae/config.py'...
***   File "./lib/python3.5/site-packages/project1/gae/config.py", line 24
    raise Exception, "For access to configuration please use get_config() function"
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/project1/gae/db'...
Compiling './lib/python3.5/site-packages/project1/gae/db/__init__.py'...
***   File "./lib/python3.5/site-packages/project1/gae/db/__init__.py", line 67
    raise RuntimeError, "Missing keys required by %s entity's "\
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/project1/gae/forms'...
Listing './lib/python3.5/site-packages/project1/gae/sceleton'...
Listing './lib/python3.5/site-packages/project1/gae/sceleton/app'...
Listing './lib/python3.5/site-packages/project1/gae/sceleton/project'...
Listing './lib/python3.5/site-packages/project1/gae/sceleton/project/apps'...
Listing './lib/python3.5/site-packages/project1/gae/sceleton/project/apps/site'...
Listing './lib/python3.5/site-packages/project1/gae/sessions'...
Compiling './lib/python3.5/site-packages/project1/gae/sessions/__init__.py'...
***   File "./lib/python3.5/site-packages/project1/gae/sessions/__init__.py", line 321
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/project1/gae/tags.py'...
***   File "./lib/python3.5/site-packages/project1/gae/tags.py", line 89
    except (AttributeError, VariableDoesNotExist), err:
                                                 ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/project1/gae/template'...
Compiling './lib/python3.5/site-packages/project1/gae/template/__init__.py'...
***   File "./lib/python3.5/site-packages/project1/gae/template/__init__.py", line 17
    except (EnvironmentError, RuntimeError), e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/project1/gae/template/loader.py'...
***   File "./lib/python3.5/site-packages/project1/gae/template/loader.py", line 35
    raise TemplateDoesNotExist, "Not specified application prefix in '%s' template path" % template_name
                              ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/project1/gae/tools'...
Compiling './lib/python3.5/site-packages/project1/gae/webapp.py'...
***   File "./lib/python3.5/site-packages/project1/gae/webapp.py", line 276
    except Request.REDIRECT, err:
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/project1/site'...
Listing './lib/python3.5/site-packages/project1/user'...
Listing './lib/python3.5/site-packages/setuptools'...
Listing './lib/python3.5/site-packages/setuptools/command'...
Listing './lib/python3.5/site-packages/setuptools/extern'...
Listing './lib/python3.5/site-packages/setuptools-32.3.1.dist-info'...
Listing './share'...
Listing './share/python-wheels'...
